<form action="{{ route('settings.public-page') }}" method="POST" class="space-y-8">
    @csrf
    @method('PUT')

    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-4">
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Testimonials Badge</label><input type="text" name="testimonials_badge_text" value="{{ old('testimonials_badge_text', $publicPage['testimonials_badge_text'] ?? 'Testimonials') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div class="md:col-span-2 xl:col-span-3"><label class="mb-2 block text-sm font-semibold text-slate-700">Testimonials Heading</label><input type="text" name="testimonials_heading" value="{{ old('testimonials_heading', $publicPage['testimonials_heading'] ?? 'What Parents and Student Say') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div class="md:col-span-2 xl:col-span-4"><label class="mb-2 block text-sm font-semibold text-slate-700">Testimonials Intro</label><input type="text" name="testimonials_subheading" value="{{ old('testimonials_subheading', $publicPage['testimonials_subheading'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Form Title</label><input type="text" name="testimonials_form_title" value="{{ old('testimonials_form_title', $publicPage['testimonials_form_title'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Name Label</label><input type="text" name="testimonials_form_name_label" value="{{ old('testimonials_form_name_label', $publicPage['testimonials_form_name_label'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Name Placeholder</label><input type="text" name="testimonials_form_name_placeholder" value="{{ old('testimonials_form_name_placeholder', $publicPage['testimonials_form_name_placeholder'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Role Label</label><input type="text" name="testimonials_form_role_label" value="{{ old('testimonials_form_role_label', $publicPage['testimonials_form_role_label'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Role Placeholder</label><input type="text" name="testimonials_form_role_placeholder" value="{{ old('testimonials_form_role_placeholder', $publicPage['testimonials_form_role_placeholder'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Rating Label</label><input type="text" name="testimonials_form_rating_label" value="{{ old('testimonials_form_rating_label', $publicPage['testimonials_form_rating_label'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Message Label</label><input type="text" name="testimonials_form_message_label" value="{{ old('testimonials_form_message_label', $publicPage['testimonials_form_message_label'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div class="md:col-span-2 xl:col-span-3"><label class="mb-2 block text-sm font-semibold text-slate-700">Message Placeholder</label><input type="text" name="testimonials_form_message_placeholder" value="{{ old('testimonials_form_message_placeholder', $publicPage['testimonials_form_message_placeholder'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Submit Button Text</label><input type="text" name="testimonials_form_submit_text" value="{{ old('testimonials_form_submit_text', $publicPage['testimonials_form_submit_text'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div><label class="mb-2 block text-sm font-semibold text-slate-700">Slider Title</label><input type="text" name="testimonials_slider_title" value="{{ old('testimonials_slider_title', $publicPage['testimonials_slider_title'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div class="md:col-span-2 xl:col-span-4"><label class="mb-2 block text-sm font-semibold text-slate-700">Empty Text</label><input type="text" name="testimonials_empty_text" value="{{ old('testimonials_empty_text', $publicPage['testimonials_empty_text'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold text-slate-700">Success Text</label><input type="text" name="testimonials_success_text" value="{{ old('testimonials_success_text', $publicPage['testimonials_success_text'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
        <div class="md:col-span-2"><label class="mb-2 block text-sm font-semibold text-slate-700">Error Text</label><input type="text" name="testimonials_error_text" value="{{ old('testimonials_error_text', $publicPage['testimonials_error_text'] ?? '') }}" class="w-full rounded-2xl border-slate-300"></div>
    </div>

    <button type="submit" class="inline-flex items-center rounded-2xl bg-[#2D1D5C] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#DFE753] hover:text-[#2D1D5C]">Save Testimonials Page</button>
</form>

